### ISSUE TITLE
[REFACTOR] 환경변수 관리

### ISSUE THREAD

**Issue by gitagita** [SEED-TEAM/SEED-SERVER#11]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] 환경변수 관리
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- .env 파일에서 환경변수를 관리한다.

## TODO

- [x] dotenv 패키지 설치(yarn add dotenv)
- [x] 루트 경로에 .env파일 생성
- [x] .gitignore파일에 .env를 추가
- [x] db.js파일에서 사용하는 DB정보를 .env파일에 저장하고 가져와서 사용한다.
