### ISSUE TITLE
[REFACTOR] 회원 관련 api 구조 변경

### ISSUE THREAD

**Issue by gitagita** [SEED-TEAM/SEED-SERVER#13]
## ✅ Refactor Request check list

- [x] 이슈 제목: [REFACTOR] '리팩토링 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 리팩토링 개요

- 회원 api에서 비밀번호를 확인하는 기능을 함수로 만들어 별도 파일로 생성(파일경로: api>user>userfunc.js)
- 메시지 담는 변수 제거하고 res.send()에서 직접 setResponse()호출하는 것으로 수정
- [GET] user/privacy와 [GET] user/privacy/:id 에서 탈퇴한 회원을 제외하는 조건 추가

## TODO

- [x] 비밀번호 확인하는 함수를 userfunc.js 파일에 구현(Promise 사용)
- [x] res.send()에서 직접 setResponse()호출하는 것으로 수정
- [x] 회원 전체 및 상세 조회 api에 탈퇴회원 제외 조건 추가
