### ISSUE TITLE
[FEATURE] 이메일 인증 api 구현

### ISSUE THREAD

**Issue by gitagita** [SEED-TEAM/SEED-SERVER#16]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- [POST] /user/auth/email
	- 이메일로 6자리 인증코드 전송
	- 클라이언트에 인증여부와 인증코드 전달

## TODO

- [x] nodemailer 설치(yarn add nodemailer)
- [x] 파일에 수신자 계정은 .env 파일에 저장
- [x] 이메일 전송 서버로 naver STMP 사용
