### ISSUE TITLE
[FEATURE] 회원정보 조회 api 구현

### ISSUE THREAD

**Issue by gitagita** [SEED-TEAM/SEED-SERVER#3]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEAT] 회원정보 조회 api 구현
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 회원 정보 조회 api
- 조회하는 값 목록: 아이디(이메일), 이름, 이미지

- [GET] /user/privacy/{userEmail}
    - userEmail 값에 해당하는 이메일(아이디)의 회원 정보 조회

- [GET] /user/privacy
    - `userEmail` params가 없는 경우 전체 회원정보 조회

## TODO

- [x] user/privacy.js에 회원 조회 api 구현

**Comment by gitagita** [comment]
yarn 설치 목록
- nodemon
- mysql
