### ISSUE TITLE
[FEATURE] 회원정보 수정 api 구현

### ISSUE THREAD

**Issue by gitagita** [SEED-TEAM/SEED-SERVER#4]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEAT] 회원정보 수정 api 구현
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 회원 정보 수정 api
- 수정하는 값 목록: 이름, 이미지

- [POST] /user/modify
    - `userEmail` 값에 해당하는 이메일(아이디)의 회원 정보 조회

## TODO

- [x] user/modify.js에 회원 조회 api 구현

**Comment by gitagita** [comment]
yarn 설치 목록
- moment
