### ISSUE TITLE
[FEATURE] 회원 등록 api 구현

### ISSUE THREAD

**Issue by gitagita** [SEED-TEAM/SEED-SERVER#5]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEAT] 회원 등록 api 구현
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 회원 등록(가입) api
- 항목: 이메일, 비밀번호, 이름, 동의항목

- [POST] /user/register
    - 이메일, 비밀번호, 이름, 동의항목 모두 필수
    - 비밀번호는 bcrypt 모듈을 사용하여 암호화

## TODO

- [x] user/register.js에 회원등록 api 구현
- [x] 비밀번호 암호화
- [x] src/app.js에 추가했던 user 관련 api를 src/routers/index.js로 옮기기

**Comment by gitagita** [comment]
yarn 설치 목록
- bcrypt
