### ISSUE TITLE
[FEATURE] 회원 등록 api에 이메일 중복 검사 추가

### ISSUE THREAD

**Issue by gitagita** [SEED-TEAM/SEED-SERVER#7]
## ✅ Feature Request check list

- [x] 이슈 제목: [ADD] 회원 등록 api에 이메일 중복 검사 추가
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 회원 등록(가입) api에 이메일 중복 검사 프로세스 추가
- 이미 가입된 이메일이 있는 경우 에러문구 반환

## TODO

- [x] user/register.js의 회원등록 api에 이메일 중복 검사 프로세스 추가
