### ISSUE TITLE
[FEATURE] 회원 탈퇴 api 구현

### ISSUE THREAD

**Issue by gitagita** [SEED-TEAM/SEED-SERVER#9]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEAT] 회원 탈퇴 api 구현
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 회원 탈퇴 api
- 항목: 이메일, 비밀번호, 탈퇴사유

- [POST] /user/delete
    - bcrypt 모듈을 이용하여 비밀번호 일치여부 확인
    - member 테이블의 withdrawal 컬럼 1로 변경
    - member_withdrawal_log 테이블에 탈퇴 정보 저장

## TODO

- [x] user/delete.js에 회원탈퇴 api 구현
- [x] 비밀번호 일치여부 확인
- [x] 탈퇴회원여부 확인
